### ISSUE TITLE
Feature Request: add esm support

### ISSUE THREAD

**Issue by xiaoxiangmoe** [feross/arch#21]
Can I create a PR to add esm support?

**Comment by xiaoxiangmoe** [comment]
@feross What is the status of this library?

**Comment by xiaoxiangmoe** [comment]
@feross Any update?

**Comment by feross** [comment]
I don't know how to add ESM support without breaking CJS. @mikeal?

**Comment by feross** [comment]
Thanks for reporting this issue. Due to time constraints, I don't have any plans to work on this so I'm going to close it. If you would like to see it implemented, please send a pull request!

![mickey-wizard](https://user-images.githubusercontent.com/121766/62907205-e7fc7680-bd26-11e9-83f3-9614f069b5e0.gif)
